# This is the default format. 
# For more see: https://github.com/mojombo/jekyll/wiki/Permalinks
permalink: /:categories/:year/:month/:day/:title 
auto: true
pygments: true
var:
  about_path: /about
  blog_path: /blog
  photos_path: /photos
  archive_path: /archive.html
  categories_path : /categories.html
  tags_path : /tags.html
  search_path : /search.html

enable_tweet_button: true  

production_url : http://pradeepnayak.in # or your custom domain name
title : Pradeep Nayak

author :
  name : Pradeep Nayak
  email : pradeep1288@gmail.com
  github : pradeep1288
  disqus_shortname: pradeepnayak
  twitter : prdpnayak
